services:
  postgres:
    image: postgres:15
    container_name: lobotomy_postgres
    restart: always
    environment:
      POSTGRES_DB: lobotomy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/schema3.sql:/docker-entrypoint-initdb.d/schema3.sql:ro

  backend:
    build: ./server
    container_name: lobotomy_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8800:8800"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: lobotomy_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
