services:
  postgres:
    image: postgres:15
    container_name: lobotomy_postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/schema3.sql:/docker-entrypoint-initdb.d/schema3.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lobotomy_db"]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 5

  genres-loader:
    build: ./server
    container_name: lobotomy_genres_loader
    command: ["node", "loadGenres.jsx"]
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  backend:
    build: ./server
    container_name: lobotomy_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8800:8800"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./client
    container_name: lobotomy_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  email-sender:
    build:
      context: ./email-notification-service
      dockerfile: Dockerfile
    container_name: email_notification_service
    restart: always
    env_file:
      - ./email-notification-service/.env
    depends_on:
      rabbitmq:
        condition: "service_healthy"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pgdata:
